services:
  superset:
    image: apachesuperset.docker.scarf.sh/apache/superset:latest-dev
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=supersecretkey
      - DATABASE_URL=postgresql+psycopg2://superset:superset@db:5432/superset
    depends_on:
      - db
    command: >
      /bin/bash -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debug
      "

  db:
    image: postgres
    container_name: superset_db
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    ports:
      - "5432:5432"
    volumes:
      - superset_db_data:/var/lib/postgresql/data

  mysql:
    image: mysql
    container_name: superset_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    ports:
      - "3306:3306"
    volumes:
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql
volumes:
  superset_db_data:
