services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ./minio:/data
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"