/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ensah.telecom.events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Represents a voice call detail record (CDR) with relevant information. */
@org.apache.avro.specific.AvroGenerated
public class VoiceCDR extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5446999065320777226L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"VoiceCDR\",\"namespace\":\"com.ensah.telecom.events\",\"doc\":\"Represents a voice call detail record (CDR) with relevant information.\",\"fields\":[{\"name\":\"record_type\",\"type\":\"string\",\"doc\":\"Type of the record (e.g., 'voice')\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Timestamp of the call\"},{\"name\":\"caller_id\",\"type\":\"string\",\"doc\":\"ID of the caller\"},{\"name\":\"callee_id\",\"type\":\"string\",\"doc\":\"ID of the callee\"},{\"name\":\"duration_sec\",\"type\":\"int\",\"doc\":\"Duration of the call in seconds\"},{\"name\":\"cell_id\",\"type\":\"string\",\"doc\":\"ID of the cell tower used\"},{\"name\":\"technology\",\"type\":\"string\",\"doc\":\"Technology used (e.g., '2G', '3G', '4G', '5G')\"},{\"name\":\"uuid\",\"type\":\"string\",\"doc\":\"Unique identifier for the call record\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<VoiceCDR> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<VoiceCDR> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<VoiceCDR> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<VoiceCDR> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<VoiceCDR> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this VoiceCDR to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a VoiceCDR from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a VoiceCDR instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static VoiceCDR fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Type of the record (e.g., 'voice') */
  private java.lang.CharSequence record_type;
  /** Timestamp of the call */
  private java.time.Instant timestamp;
  /** ID of the caller */
  private java.lang.CharSequence caller_id;
  /** ID of the callee */
  private java.lang.CharSequence callee_id;
  /** Duration of the call in seconds */
  private int duration_sec;
  /** ID of the cell tower used */
  private java.lang.CharSequence cell_id;
  /** Technology used (e.g., '2G', '3G', '4G', '5G') */
  private java.lang.CharSequence technology;
  /** Unique identifier for the call record */
  private java.lang.CharSequence uuid;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public VoiceCDR() {}

  /**
   * All-args constructor.
   * @param record_type Type of the record (e.g., 'voice')
   * @param timestamp Timestamp of the call
   * @param caller_id ID of the caller
   * @param callee_id ID of the callee
   * @param duration_sec Duration of the call in seconds
   * @param cell_id ID of the cell tower used
   * @param technology Technology used (e.g., '2G', '3G', '4G', '5G')
   * @param uuid Unique identifier for the call record
   */
  public VoiceCDR(java.lang.CharSequence record_type, java.time.Instant timestamp, java.lang.CharSequence caller_id, java.lang.CharSequence callee_id, java.lang.Integer duration_sec, java.lang.CharSequence cell_id, java.lang.CharSequence technology, java.lang.CharSequence uuid) {
    this.record_type = record_type;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.caller_id = caller_id;
    this.callee_id = callee_id;
    this.duration_sec = duration_sec;
    this.cell_id = cell_id;
    this.technology = technology;
    this.uuid = uuid;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return record_type;
    case 1: return timestamp;
    case 2: return caller_id;
    case 3: return callee_id;
    case 4: return duration_sec;
    case 5: return cell_id;
    case 6: return technology;
    case 7: return uuid;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: record_type = (java.lang.CharSequence)value$; break;
    case 1: timestamp = (java.time.Instant)value$; break;
    case 2: caller_id = (java.lang.CharSequence)value$; break;
    case 3: callee_id = (java.lang.CharSequence)value$; break;
    case 4: duration_sec = (java.lang.Integer)value$; break;
    case 5: cell_id = (java.lang.CharSequence)value$; break;
    case 6: technology = (java.lang.CharSequence)value$; break;
    case 7: uuid = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'record_type' field.
   * @return Type of the record (e.g., 'voice')
   */
  public java.lang.CharSequence getRecordType() {
    return record_type;
  }


  /**
   * Sets the value of the 'record_type' field.
   * Type of the record (e.g., 'voice')
   * @param value the value to set.
   */
  public void setRecordType(java.lang.CharSequence value) {
    this.record_type = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Timestamp of the call
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Timestamp of the call
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'caller_id' field.
   * @return ID of the caller
   */
  public java.lang.CharSequence getCallerId() {
    return caller_id;
  }


  /**
   * Sets the value of the 'caller_id' field.
   * ID of the caller
   * @param value the value to set.
   */
  public void setCallerId(java.lang.CharSequence value) {
    this.caller_id = value;
  }

  /**
   * Gets the value of the 'callee_id' field.
   * @return ID of the callee
   */
  public java.lang.CharSequence getCalleeId() {
    return callee_id;
  }


  /**
   * Sets the value of the 'callee_id' field.
   * ID of the callee
   * @param value the value to set.
   */
  public void setCalleeId(java.lang.CharSequence value) {
    this.callee_id = value;
  }

  /**
   * Gets the value of the 'duration_sec' field.
   * @return Duration of the call in seconds
   */
  public int getDurationSec() {
    return duration_sec;
  }


  /**
   * Sets the value of the 'duration_sec' field.
   * Duration of the call in seconds
   * @param value the value to set.
   */
  public void setDurationSec(int value) {
    this.duration_sec = value;
  }

  /**
   * Gets the value of the 'cell_id' field.
   * @return ID of the cell tower used
   */
  public java.lang.CharSequence getCellId() {
    return cell_id;
  }


  /**
   * Sets the value of the 'cell_id' field.
   * ID of the cell tower used
   * @param value the value to set.
   */
  public void setCellId(java.lang.CharSequence value) {
    this.cell_id = value;
  }

  /**
   * Gets the value of the 'technology' field.
   * @return Technology used (e.g., '2G', '3G', '4G', '5G')
   */
  public java.lang.CharSequence getTechnology() {
    return technology;
  }


  /**
   * Sets the value of the 'technology' field.
   * Technology used (e.g., '2G', '3G', '4G', '5G')
   * @param value the value to set.
   */
  public void setTechnology(java.lang.CharSequence value) {
    this.technology = value;
  }

  /**
   * Gets the value of the 'uuid' field.
   * @return Unique identifier for the call record
   */
  public java.lang.CharSequence getUuid() {
    return uuid;
  }


  /**
   * Sets the value of the 'uuid' field.
   * Unique identifier for the call record
   * @param value the value to set.
   */
  public void setUuid(java.lang.CharSequence value) {
    this.uuid = value;
  }

  /**
   * Creates a new VoiceCDR RecordBuilder.
   * @return A new VoiceCDR RecordBuilder
   */
  public static com.ensah.telecom.events.VoiceCDR.Builder newBuilder() {
    return new com.ensah.telecom.events.VoiceCDR.Builder();
  }

  /**
   * Creates a new VoiceCDR RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new VoiceCDR RecordBuilder
   */
  public static com.ensah.telecom.events.VoiceCDR.Builder newBuilder(com.ensah.telecom.events.VoiceCDR.Builder other) {
    if (other == null) {
      return new com.ensah.telecom.events.VoiceCDR.Builder();
    } else {
      return new com.ensah.telecom.events.VoiceCDR.Builder(other);
    }
  }

  /**
   * Creates a new VoiceCDR RecordBuilder by copying an existing VoiceCDR instance.
   * @param other The existing instance to copy.
   * @return A new VoiceCDR RecordBuilder
   */
  public static com.ensah.telecom.events.VoiceCDR.Builder newBuilder(com.ensah.telecom.events.VoiceCDR other) {
    if (other == null) {
      return new com.ensah.telecom.events.VoiceCDR.Builder();
    } else {
      return new com.ensah.telecom.events.VoiceCDR.Builder(other);
    }
  }

  /**
   * RecordBuilder for VoiceCDR instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<VoiceCDR>
    implements org.apache.avro.data.RecordBuilder<VoiceCDR> {

    /** Type of the record (e.g., 'voice') */
    private java.lang.CharSequence record_type;
    /** Timestamp of the call */
    private java.time.Instant timestamp;
    /** ID of the caller */
    private java.lang.CharSequence caller_id;
    /** ID of the callee */
    private java.lang.CharSequence callee_id;
    /** Duration of the call in seconds */
    private int duration_sec;
    /** ID of the cell tower used */
    private java.lang.CharSequence cell_id;
    /** Technology used (e.g., '2G', '3G', '4G', '5G') */
    private java.lang.CharSequence technology;
    /** Unique identifier for the call record */
    private java.lang.CharSequence uuid;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ensah.telecom.events.VoiceCDR.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.record_type)) {
        this.record_type = data().deepCopy(fields()[0].schema(), other.record_type);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.caller_id)) {
        this.caller_id = data().deepCopy(fields()[2].schema(), other.caller_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.callee_id)) {
        this.callee_id = data().deepCopy(fields()[3].schema(), other.callee_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.duration_sec)) {
        this.duration_sec = data().deepCopy(fields()[4].schema(), other.duration_sec);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.cell_id)) {
        this.cell_id = data().deepCopy(fields()[5].schema(), other.cell_id);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.technology)) {
        this.technology = data().deepCopy(fields()[6].schema(), other.technology);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.uuid)) {
        this.uuid = data().deepCopy(fields()[7].schema(), other.uuid);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing VoiceCDR instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ensah.telecom.events.VoiceCDR other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.record_type)) {
        this.record_type = data().deepCopy(fields()[0].schema(), other.record_type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.caller_id)) {
        this.caller_id = data().deepCopy(fields()[2].schema(), other.caller_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.callee_id)) {
        this.callee_id = data().deepCopy(fields()[3].schema(), other.callee_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.duration_sec)) {
        this.duration_sec = data().deepCopy(fields()[4].schema(), other.duration_sec);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.cell_id)) {
        this.cell_id = data().deepCopy(fields()[5].schema(), other.cell_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.technology)) {
        this.technology = data().deepCopy(fields()[6].schema(), other.technology);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.uuid)) {
        this.uuid = data().deepCopy(fields()[7].schema(), other.uuid);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'record_type' field.
      * Type of the record (e.g., 'voice')
      * @return The value.
      */
    public java.lang.CharSequence getRecordType() {
      return record_type;
    }


    /**
      * Sets the value of the 'record_type' field.
      * Type of the record (e.g., 'voice')
      * @param value The value of 'record_type'.
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder setRecordType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.record_type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'record_type' field has been set.
      * Type of the record (e.g., 'voice')
      * @return True if the 'record_type' field has been set, false otherwise.
      */
    public boolean hasRecordType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'record_type' field.
      * Type of the record (e.g., 'voice')
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder clearRecordType() {
      record_type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Timestamp of the call
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Timestamp of the call
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[1], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Timestamp of the call
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Timestamp of the call
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'caller_id' field.
      * ID of the caller
      * @return The value.
      */
    public java.lang.CharSequence getCallerId() {
      return caller_id;
    }


    /**
      * Sets the value of the 'caller_id' field.
      * ID of the caller
      * @param value The value of 'caller_id'.
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder setCallerId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.caller_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'caller_id' field has been set.
      * ID of the caller
      * @return True if the 'caller_id' field has been set, false otherwise.
      */
    public boolean hasCallerId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'caller_id' field.
      * ID of the caller
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder clearCallerId() {
      caller_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'callee_id' field.
      * ID of the callee
      * @return The value.
      */
    public java.lang.CharSequence getCalleeId() {
      return callee_id;
    }


    /**
      * Sets the value of the 'callee_id' field.
      * ID of the callee
      * @param value The value of 'callee_id'.
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder setCalleeId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.callee_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'callee_id' field has been set.
      * ID of the callee
      * @return True if the 'callee_id' field has been set, false otherwise.
      */
    public boolean hasCalleeId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'callee_id' field.
      * ID of the callee
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder clearCalleeId() {
      callee_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'duration_sec' field.
      * Duration of the call in seconds
      * @return The value.
      */
    public int getDurationSec() {
      return duration_sec;
    }


    /**
      * Sets the value of the 'duration_sec' field.
      * Duration of the call in seconds
      * @param value The value of 'duration_sec'.
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder setDurationSec(int value) {
      validate(fields()[4], value);
      this.duration_sec = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'duration_sec' field has been set.
      * Duration of the call in seconds
      * @return True if the 'duration_sec' field has been set, false otherwise.
      */
    public boolean hasDurationSec() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'duration_sec' field.
      * Duration of the call in seconds
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder clearDurationSec() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'cell_id' field.
      * ID of the cell tower used
      * @return The value.
      */
    public java.lang.CharSequence getCellId() {
      return cell_id;
    }


    /**
      * Sets the value of the 'cell_id' field.
      * ID of the cell tower used
      * @param value The value of 'cell_id'.
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder setCellId(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.cell_id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'cell_id' field has been set.
      * ID of the cell tower used
      * @return True if the 'cell_id' field has been set, false otherwise.
      */
    public boolean hasCellId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'cell_id' field.
      * ID of the cell tower used
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder clearCellId() {
      cell_id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'technology' field.
      * Technology used (e.g., '2G', '3G', '4G', '5G')
      * @return The value.
      */
    public java.lang.CharSequence getTechnology() {
      return technology;
    }


    /**
      * Sets the value of the 'technology' field.
      * Technology used (e.g., '2G', '3G', '4G', '5G')
      * @param value The value of 'technology'.
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder setTechnology(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.technology = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'technology' field has been set.
      * Technology used (e.g., '2G', '3G', '4G', '5G')
      * @return True if the 'technology' field has been set, false otherwise.
      */
    public boolean hasTechnology() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'technology' field.
      * Technology used (e.g., '2G', '3G', '4G', '5G')
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder clearTechnology() {
      technology = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'uuid' field.
      * Unique identifier for the call record
      * @return The value.
      */
    public java.lang.CharSequence getUuid() {
      return uuid;
    }


    /**
      * Sets the value of the 'uuid' field.
      * Unique identifier for the call record
      * @param value The value of 'uuid'.
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder setUuid(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.uuid = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'uuid' field has been set.
      * Unique identifier for the call record
      * @return True if the 'uuid' field has been set, false otherwise.
      */
    public boolean hasUuid() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'uuid' field.
      * Unique identifier for the call record
      * @return This builder.
      */
    public com.ensah.telecom.events.VoiceCDR.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public VoiceCDR build() {
      try {
        VoiceCDR record = new VoiceCDR();
        record.record_type = fieldSetFlags()[0] ? this.record_type : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.time.Instant) defaultValue(fields()[1]);
        record.caller_id = fieldSetFlags()[2] ? this.caller_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.callee_id = fieldSetFlags()[3] ? this.callee_id : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.duration_sec = fieldSetFlags()[4] ? this.duration_sec : (java.lang.Integer) defaultValue(fields()[4]);
        record.cell_id = fieldSetFlags()[5] ? this.cell_id : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.technology = fieldSetFlags()[6] ? this.technology : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.uuid = fieldSetFlags()[7] ? this.uuid : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<VoiceCDR>
    WRITER$ = (org.apache.avro.io.DatumWriter<VoiceCDR>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<VoiceCDR>
    READER$ = (org.apache.avro.io.DatumReader<VoiceCDR>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










